#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.allocation_info
short_description: Retrieve Allocation information
description:
- Allocations are the mechanism by which Provider can delegate Network and Compute resources to Tenant.
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  allocation_constraint_id:
    type: str
    description:
    - 'ID path parameter: allocation_constraint_id.'
  allocation_id:
    type: str
    description:
    - 'ID path parameter: allocation_id.'
  constraint_type:
    type: str
    description:
    - Filter Allocations by Constraint Type.  Can be specified multiple times to filter on more than one Constraint Type.
    choices:
    - Reserved
    - OnDemand
    - Preemptible
  constraint_value:
    type: int
    description:
    - Filter Allocations by Constraint Value.  Can be specified multiple times to filter on more than one Constraint Value.
  id:
    type: str
    description:
    - Filter Allocations by ID.  Can be specified multiple times to filter on more than one ID.
  infrastructure_provider_id:
    type: str
    description:
    - Filter Allocations by Infrastructure Provider ID.
  query:
    type: str
    description:
    - Search for matches across all Sites. Input will be matched against name, description and status fields
  resource_type:
    type: str
    description:
    - Filter Allocations by Constraint Resource Type.  Can be specified multiple times to filter on more than one Constraint
      Resource Type.
    choices:
    - InstanceType
    - IPBlock
  resource_type_id:
    type: str
    description:
    - Filter Allocations by Constraint Resource Type ID.  Can be specified multiple times to filter on more than one Constraint
      Resource Type ID.
  site_id:
    type: str
    description:
    - Filter Allocations by Site ID.  Can be specified multiple times to filter on more than one Site ID.
  status:
    type: str
    description:
    - Filter Allocations by Status.  Can be specified multiple times to filter on more than one Status.
  tenant_id:
    type: str
    description:
    - Filter Allocations by Tenant ID.
'''

EXAMPLES = r'''
---
- name: List all Allocation resources
  nvidia.infra_controller.allocation_info:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"

- name: Get a specific Allocation by ID
  nvidia.infra_controller.allocation_info:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    id: "{{ resource_id }}"
'''

RETURN = r'''
---
resources:
    description: List of resources.
    type: list
    returned: when no id is specified
    elements: dict
resource:
    description: Single resource details.
    type: dict
    returned: when id is specified
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import InfoResource


ARGUMENT_SPEC = dict(
allocation_constraint_id=dict(type='str'),
allocation_id=dict(type='str'),
constraint_type=dict(type='str', choices=['Reserved', 'OnDemand', 'Preemptible']),
constraint_value=dict(type='int'),
id=dict(type='str'),
infrastructure_provider_id=dict(type='str'),
query=dict(type='str'),
resource_type=dict(type='str', choices=['InstanceType', 'IPBlock']),
resource_type_id=dict(type='str'),
site_id=dict(type='str'),
status=dict(type='str'),
tenant_id=dict(type='str'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/allocation',
    'resource_item_path': '/v2/org/{org}/nico/allocation/{allocationId}/constraint/{allocationConstraintId}',
    'id_param': 'allocationConstraintId',
    'filter_fields': ['infrastructure_provider_id', 'tenant_id', 'site_id', 'id', 'resource_type', 'status', 'resource_type_id', 'constraint_type', 'constraint_value', 'query'],
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    InfoResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
