#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.allocation
short_description: Manage Allocation resources
description:
- Allocations are the mechanism by which Provider can delegate Network and Compute resources to Tenant.
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  allocation_constraint_id:
    type: str
    description:
    - 'ID path parameter: allocation_constraint_id.'
  allocation_constraints:
    type: list
    description:
    - List of Allocation Constraint objects
    elements: dict
    suboptions:
      constraint_type:
        type: str
        description:
        - constraint_type parameter.
        required: true
        choices:
        - Reserved
        - OnDemand
        - Preemptible
      constraint_value:
        type: int
        description:
        - constraint_value parameter.
        required: true
      resource_type:
        type: str
        description:
        - resource_type parameter.
        required: true
        choices:
        - InstanceType
        - IPBlock
      resource_type_id:
        type: str
        description:
        - resource_type_id parameter.
        required: true
  allocation_id:
    type: str
    description:
    - 'ID path parameter: allocation_id.'
  constraint_value:
    type: int
    description:
    - Value of the Allocation Constraint. For InstanceType, this value represents number of Machines allocated for Tenant.
      For IPBlock, this value represents the prefix Length of the IP Block.
  description:
    type: str
    description:
    - Detailed description for the Allocation
  id:
    type: str
    description:
    - ID of the resource. Used for lookup.
  name:
    type: str
    description:
    - Concise and descriptive name for the Allocation
  site_id:
    type: str
    description:
    - ID of the Site where resources should be allocated
  state:
    type: str
    description:
    - Desired state of the resource.
    choices:
    - present
    - absent
  tenant_id:
    type: str
    description:
    - ID of the Tenant that should receive the Allocation
  wait:
    type: bool
    description:
    - Wait for the resource to reach the desired state.
  wait_timeout:
    type: int
    description:
    - Timeout in seconds for wait operations.
'''

EXAMPLES = r'''
---
- name: Create a Allocation
  nvidia.infra_controller.allocation:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: present
    name: "my-allocation"

- name: Delete a Allocation
  nvidia.infra_controller.allocation:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: absent
    name: "my-allocation"
'''

RETURN = r'''
---
resource:
    description: The resource details.
    type: dict
    returned: when state is present
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import CrudResource


ARGUMENT_SPEC = dict(
allocation_constraint_id=dict(type='str'),
allocation_constraints=dict(type='list', elements='dict', options=dict(
    constraint_type=dict(type='str', required=True, choices=['Reserved', 'OnDemand', 'Preemptible']),
    constraint_value=dict(type='int', required=True),
    resource_type=dict(type='str', required=True, choices=['InstanceType', 'IPBlock']),
    resource_type_id=dict(type='str', required=True),
)),
allocation_id=dict(type='str'),
constraint_value=dict(type='int'),
description=dict(type='str'),
id=dict(type='str'),
name=dict(type='str'),
site_id=dict(type='str'),
state=dict(type='str', choices=['present', 'absent']),
tenant_id=dict(type='str'),
wait=dict(type='bool'),
wait_timeout=dict(type='int'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/allocation',
    'resource_item_path': '/v2/org/{org}/nico/allocation/{allocationId}/constraint/{allocationConstraintId}',
    'id_param': 'allocationConstraintId',
    'name_field': 'name',
    'create_schema_fields': ['name', 'description', 'tenant_id', 'site_id', 'allocation_constraints'],
    'update_schema_fields': ['constraint_value'],
    'scope_fields': ['site_id'],
    'ready_statuses': ['Ready'],
    'error_statuses': ['Error'],
    'no_create': False,
    'delete_body_fields': [],
    'version_field': None,
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    CrudResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
