#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.credential_rotation_info
short_description: Retrieve Credential Rotation information
description:
- Credential Rotation endpoints stage a site-wide credential rotation and report per-Site or per-device convergence
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  credential_type:
    type: str
    description:
    - Credential family to report.
    choices:
    - BMC
    - HostUEFI
    - DPUUEFI
    - NVOS
    - LockdownIKM
  device_mac:
    type: str
    description:
    - Report only this device's convergence, matched by MAC.
  site_id:
    type: str
    description:
    - ID of the Site to query.
'''

EXAMPLES = r'''
---
- name: List all Credential Rotation resources
  nvidia.infra_controller.credential_rotation_info:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"

- name: Get a specific Credential Rotation by ID
  nvidia.infra_controller.credential_rotation_info:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    id: "{{ resource_id }}"
'''

RETURN = r'''
---
resources:
    description: List of resources.
    type: list
    returned: when no id is specified
    elements: dict
resource:
    description: Single resource details.
    type: dict
    returned: when id is specified
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import InfoResource


ARGUMENT_SPEC = dict(
credential_type=dict(type='str', choices=['BMC', 'HostUEFI', 'DPUUEFI', 'NVOS', 'LockdownIKM']),
device_mac=dict(type='str'),
site_id=dict(type='str'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/credential/rotation',
    'resource_item_path': '',
    'id_param': 'id',
    'filter_fields': ['site_id', 'credential_type', 'device_mac'],
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    InfoResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
