#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.credential_rotation
short_description: Manage Credential Rotation resources
description:
- Credential Rotation endpoints stage a site-wide credential rotation and report per-Site or per-device convergence
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  credential_type:
    type: str
    description:
    - Credential family to rotate.
    choices:
    - BMC
    - HostUEFI
    - DPUUEFI
    - NVOS
    - LockdownIKM
  id:
    type: str
    description:
    - ID of the resource. Used for lookup.
  password:
    type: str
    description:
    - Explicit rotate-to password. When omitted, a strong password is auto-generated. Never returned.
  reason:
    type: str
    description:
    - Free-form operator note recorded with the rotation. Must not contain secrets.
  site_id:
    type: str
    description:
    - ID of the Site whose credential family is rotated.
  state:
    type: str
    description:
    - Desired state of the resource.
    choices:
    - present
    - absent
  wait:
    type: bool
    description:
    - Wait for the resource to reach the desired state.
  wait_timeout:
    type: int
    description:
    - Timeout in seconds for wait operations.
'''

EXAMPLES = r'''
---
- name: Create a Credential Rotation
  nvidia.infra_controller.credential_rotation:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: present
    name: "my-credential-rotation"

- name: Delete a Credential Rotation
  nvidia.infra_controller.credential_rotation:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: absent
    name: "my-credential-rotation"
'''

RETURN = r'''
---
resource:
    description: The resource details.
    type: dict
    returned: when state is present
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import CrudResource


ARGUMENT_SPEC = dict(
credential_type=dict(type='str', choices=['BMC', 'HostUEFI', 'DPUUEFI', 'NVOS', 'LockdownIKM']),
id=dict(type='str'),
password=dict(type='str'),
reason=dict(type='str'),
site_id=dict(type='str'),
state=dict(type='str', choices=['present', 'absent']),
wait=dict(type='bool'),
wait_timeout=dict(type='int'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/credential/rotation',
    'resource_item_path': '',
    'id_param': 'id',
    'name_field': None,
    'create_schema_fields': ['site_id', 'credential_type', 'password', 'reason'],
    'update_schema_fields': [],
    'scope_fields': [],
    'ready_statuses': ['Ready'],
    'error_statuses': ['Error'],
    'no_create': False,
    'delete_body_fields': [],
    'version_field': None,
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    CrudResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
