#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.dpu_machine_info
short_description: Retrieve DPU Machine information
description:
- A DPU (Data Processing Unit) is a programmable network device installed in a Machine that runs its own operating system,
  so NICo tracks each DPU as a Machine of its own alongside the host Machine it is attached to. NICo provisions the DPU and
  uses it to enforce network isolation and Machine trust for the host, including when that host moves between Tenants.
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  dpu_machine_id:
    type: str
    description:
    - 'ID path parameter: dpu_machine_id.'
  id:
    type: str
    description:
    - ID of the resource to retrieve.
  site_id:
    type: str
    description:
    - ID of the Site
'''

EXAMPLES = r'''
---
- name: List all DPU Machine resources
  nvidia.infra_controller.dpu_machine_info:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"

- name: Get a specific DPU Machine by ID
  nvidia.infra_controller.dpu_machine_info:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    id: "{{ resource_id }}"
'''

RETURN = r'''
---
resources:
    description: List of resources.
    type: list
    returned: when no id is specified
    elements: dict
resource:
    description: Single resource details.
    type: dict
    returned: when id is specified
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import InfoResource


ARGUMENT_SPEC = dict(
dpu_machine_id=dict(type='str'),
id=dict(type='str'),
site_id=dict(type='str'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/dpu',
    'resource_item_path': '/v2/org/{org}/nico/dpu/{dpuMachineId}',
    'id_param': 'dpuMachineId',
    'filter_fields': ['site_id'],
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    InfoResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
