#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.expected_rack
short_description: Manage Expected Rack resources
description:
- 'Expected Rack identifies a Rack that is expected to be discovered at a Site. Infrastructure Providers can pre-register
  Expected Racks with an operator-supplied

  rack identifier and a Rack Profile reference to help with Rack discovery and ingestion. Chassis identity and physical location
  information are conveyed via

  well-known label keys (`chassis.manufacturer`, `chassis.serial-number`, `chassis.model`, `location.region`, `location.datacenter`,
  `location.room`, `location.position`).'
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  description:
    type: str
    description:
    - Human-readable description of the Expected Rack
  id:
    type: str
    description:
    - ID of the resource. Used for lookup.
  labels:
    type: dict
    description:
    - User-defined key-value pairs for organizing and categorizing Expected Racks. Well-known keys (`chassis.*`, `location.*`)
      are used to convey chassis identity and physical location.
  name:
    type: str
    description:
    - Human-readable name of the Expected Rack
  rack_id:
    type: str
    description:
    - Operator-supplied identifier for the rack (string, not UUID). Must be non-empty and unique within the Site.
  rack_profile_id:
    type: str
    description:
    - Identifier of the Rack Profile this rack conforms to. Must be non-empty.
  site_id:
    type: str
    description:
    - ID of the Site the Expected Rack belongs to
  state:
    type: str
    description:
    - Desired state of the resource.
    choices:
    - present
    - absent
  wait:
    type: bool
    description:
    - Wait for the resource to reach the desired state.
  wait_timeout:
    type: int
    description:
    - Timeout in seconds for wait operations.
'''

EXAMPLES = r'''
---
- name: Create a Expected Rack
  nvidia.infra_controller.expected_rack:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: present
    name: "my-expected-rack"

- name: Delete a Expected Rack
  nvidia.infra_controller.expected_rack:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: absent
    name: "my-expected-rack"
'''

RETURN = r'''
---
resource:
    description: The resource details.
    type: dict
    returned: when state is present
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import CrudResource


ARGUMENT_SPEC = dict(
description=dict(type='str'),
id=dict(type='str'),
labels=dict(type='dict'),
name=dict(type='str'),
rack_id=dict(type='str'),
rack_profile_id=dict(type='str'),
site_id=dict(type='str'),
state=dict(type='str', choices=['present', 'absent']),
wait=dict(type='bool'),
wait_timeout=dict(type='int'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/expected-rack/all',
    'resource_item_path': '/v2/org/{org}/nico/expected-rack/{id}',
    'id_param': 'id',
    'name_field': 'name',
    'create_schema_fields': ['site_id', 'rack_id', 'rack_profile_id', 'name', 'description', 'labels'],
    'update_schema_fields': ['id', 'rack_id', 'rack_profile_id', 'name', 'description', 'labels'],
    'scope_fields': [],
    'ready_statuses': ['Ready'],
    'error_statuses': ['Error'],
    'no_create': False,
    'delete_body_fields': [],
    'version_field': None,
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    CrudResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
