#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.health_report
short_description: Manage Health Report resources
description:
- Machine Health Report contains information about the health of a Machine including user enforced overrides
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  id:
    type: str
    description:
    - ID of the resource. Used for lookup.
  machine_id:
    type: str
    description:
    - 'ID path parameter: machine_id.'
  source:
    type: str
    description:
    - 'ID path parameter: source.'
  state:
    type: str
    description:
    - Desired state of the resource.
    choices:
    - present
    - absent
  wait:
    type: bool
    description:
    - Wait for the resource to reach the desired state.
  wait_timeout:
    type: int
    description:
    - Timeout in seconds for wait operations.
'''

EXAMPLES = r'''
---
- name: Delete a Health Report
  nvidia.infra_controller.health_report:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: absent
    id: "{{ resource_id }}"
'''

RETURN = r'''
---
resource:
    description: The resource details.
    type: dict
    returned: when state is present
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import CrudResource


ARGUMENT_SPEC = dict(
id=dict(type='str'),
machine_id=dict(type='str'),
source=dict(type='str'),
state=dict(type='str', choices=['present', 'absent']),
wait=dict(type='bool'),
wait_timeout=dict(type='int'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/machine/{machineId}/health-report',
    'resource_item_path': '/v2/org/{org}/nico/machine/{machineId}/health-report/{source}',
    'id_param': 'source',
    'name_field': None,
    'create_schema_fields': [],
    'update_schema_fields': [],
    'scope_fields': [],
    'ready_statuses': ['Ready'],
    'error_statuses': ['Error'],
    'no_create': False,
    'delete_body_fields': [],
    'version_field': None,
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    CrudResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
