#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.i_pxe_template_info
short_description: Retrieve iPXE Template information
description:
- iPXE Templates are read-only definitions propagated from nico-core into the REST API. Each template has a stable core UUID
  and a globally unique name; per-site availability is tracked in IpxeTemplateSiteAssociation records rather than on the template
  row itself. List and retrieve operations return templates reported at sites the caller is authorized for (optionally filtered
  by `siteId`). Templated iPXE Operating Systems reference a template by `ipxeTemplateId`.
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  id:
    type: str
    description:
    - ID of the resource to retrieve.
  ipxe_template_id:
    type: str
    description:
    - 'ID path parameter: ipxe_template_id.'
  site_id:
    type: list
    description:
    - Optional site ID(s); may be repeated to restrict results to templates available at any of the sites
    elements: str
'''

EXAMPLES = r'''
---
- name: List all iPXE Template resources
  nvidia.infra_controller.i_pxe_template_info:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"

- name: Get a specific iPXE Template by ID
  nvidia.infra_controller.i_pxe_template_info:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    id: "{{ resource_id }}"
'''

RETURN = r'''
---
resources:
    description: List of resources.
    type: list
    returned: when no id is specified
    elements: dict
resource:
    description: Single resource details.
    type: dict
    returned: when id is specified
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import InfoResource


ARGUMENT_SPEC = dict(
id=dict(type='str'),
ipxe_template_id=dict(type='str'),
site_id=dict(type='list', elements='str'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/ipxe-template',
    'resource_item_path': '/v2/org/{org}/nico/ipxe-template/{ipxeTemplateId}',
    'id_param': 'ipxeTemplateId',
    'filter_fields': ['site_id'],
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    InfoResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
