#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.instance
short_description: Manage Instance resources
description:
- Instance is a Machine provisioned with an Operating System by a Tenant and attached to one or more VPC Prefixes or Subnets.
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  always_boot_with_custom_ipxe:
    type: bool
    description:
    - When set to true, the iPXE script specified by OS or overridden here will always be run when rebooting the Instances.
      OS must be of iPXE type.
  apply_updates_on_reboot:
    type: bool
    description:
    - When specified, any updates pending for the Instance e.g. DPU reprovisioning, will be applied on reboot
  auto_network:
    type: bool
    description:
    - 'When true, asks NICo to auto-resolve each Instance''s network interfaces from the host''s underlay (HostInband) network
      segments. Intended for instances on zero-DPU hosts (or hosts with their DPU in NIC mode). When true: (1) the target
      VPC''s `networkVirtualizationType` MUST be `FLAT`, (2) `interfaces` MUST be empty or omitted, and (3) `secondaryVpcIds`
      MUST be empty or omitted.'
  count:
    type: int
    description:
    - Number of instances to create in this batch. Minimum 2, maximum 18 (limited by topology domain size)
  description:
    type: str
    description:
    - Description applied to all instances in the batch, optional
  dpu_extension_service_deployments:
    type: list
    description:
    - DPU Extension Services to deploy to all instances in the batch
    elements: dict
    suboptions:
      dpu_extension_service_id:
        type: str
        description:
        - dpu_extension_service_id parameter.
      version:
        type: str
        description:
        - version parameter.
  id:
    type: str
    description:
    - ID of the resource. Used for lookup.
  infiniband_interfaces:
    type: list
    description:
    - InfiniBand interface configuration shared across all instances
    elements: dict
    suboptions:
      device:
        type: str
        description:
        - device parameter.
      device_instance:
        type: int
        description:
        - device_instance parameter.
      is_physical:
        type: bool
        description:
        - is_physical parameter.
      partition_id:
        type: str
        description:
        - partition_id parameter.
      vendor:
        type: str
        description:
        - vendor parameter.
      virtual_function_id:
        type: int
        description:
        - virtual_function_id parameter.
  instance_id:
    type: str
    description:
    - 'ID path parameter: instance_id.'
  instance_type_id:
    type: str
    description:
    - ID of the Instance Type to use for all Instances in the batch
  interfaces:
    type: list
    description:
    - 'Interface configuration shared across all instances. At least one interface must be specified unless `autoNetwork`
      is true. Either Subnet or VPC Prefix interfaces allowed, only one of the Subnets or VPC Prefixes can be attached over
      Physical interface. Interface `ipAddress` is not supported for batch instance creation requests. Mutually exclusive
      with `autoNetwork`: when `autoNetwork` is true this list MUST be empty.'
    elements: dict
    suboptions:
      device:
        type: str
        description:
        - device parameter.
      device_instance:
        type: int
        description:
        - device_instance parameter.
      inline_routing_profile:
        type: str
        description:
        - inline_routing_profile parameter.
      ip_address:
        type: str
        description:
        - ip_address parameter.
      is_physical:
        type: bool
        description:
        - is_physical parameter.
      subnet_id:
        type: str
        description:
        - subnet_id parameter.
      virtual_function_id:
        type: int
        description:
        - virtual_function_id parameter.
      vpc_prefix_id:
        type: str
        description:
        - vpc_prefix_id parameter.
  ipxe_script:
    type: str
    description:
    - Override iPXE script specified in OS, must be specified if Operating System is not specified
  is_repair_tenant:
    type: bool
    description:
    - Should be set to true for Tenants who are performing investigation/repairing the Machine. Otherwise omit or set to false
  labels:
    type: dict
    description:
    - labels parameter.
  machine_health_issue:
    type: dict
    description:
    - Information regarding issue with the underlying Machine experienced by Tenant
    suboptions:
      category:
        type: str
        description:
        - category parameter.
        required: true
        choices:
        - Hardware
        - Network
        - Performance
        - Storage
        - Software
        - Other
      details:
        type: str
        description:
        - details parameter.
        required: true
      summary:
        type: str
        description:
        - summary parameter.
        required: true
  name:
    type: str
    description:
    - Updated name for the Instance
  name_prefix:
    type: str
    description:
    - Prefix for instance names. Instances will be named with this prefix followed by a random 6-character suffix (e.g., "worker"
      becomes "worker-abc123")
  network_security_group_id:
    type: str
    description:
    - ID of a Network Security Group to attach to all instances
  nv_link_interfaces:
    type: list
    description:
    - NVLink interface configuration shared across all instances. A subset of GPUs may be specified. Each item references
      one GPU index (`deviceInstance`) and one NVLink Logical Partition. Different interfaces may reference different NVLink
      Logical Partitions.
    elements: dict
    suboptions:
      device_instance:
        type: int
        description:
        - device_instance parameter.
      nv_linklogical_partition_id:
        type: str
        description:
        - nv_linklogical_partition_id parameter.
  operating_system_id:
    type: str
    description:
    - Must be specified if iPXE Script field is empty
  phone_home_enabled:
    type: bool
    description:
    - When set to true, the Instances will be enabled with the Phone Home service.
  reboot_with_custom_ipxe:
    type: bool
    description:
    - When specified along with triggerReboot, the Instance will boot using the custom iPXE specified by OS. If Instance has
      alwaysBootWithCustomIpxe flag set then this value will be ignored.
  secondary_vpc_ids:
    type: list
    description:
    - IDs of additional VPCs the Instances should attach to through non-primary interfaces. This field may only be specified
      when every entry in `interfaces` uses `vpcPrefixId`. IDs must be unique, must be valid UUIDs, and must not include the
      primary `vpcId`.
    elements: str
  ssh_key_group_ids:
    type: list
    description:
    - SSH Key Group IDs that will provide Serial over LAN access to all instances
    elements: str
  state:
    type: str
    description:
    - Desired state of the resource.
    choices:
    - present
    - absent
  tenant_id:
    type: str
    description:
    - ID of the Tenant creating the Instances
  topology_optimized:
    type: bool
    description:
    - When true (default), all instances must be allocated on machines within the same NVLink domain. When false, instances
      can be spread across different NVLink domains.
  trigger_reboot:
    type: bool
    description:
    - Trigger power cycle for Instance
  user_data:
    type: str
    description:
    - User data applied to all instances. Can only be specified if allowOverride is set to true in Operating System
  vpc_id:
    type: str
    description:
    - ID of the VPC the Instances should belong to
  wait:
    type: bool
    description:
    - Wait for the resource to reach the desired state.
  wait_timeout:
    type: int
    description:
    - Timeout in seconds for wait operations.
'''

EXAMPLES = r'''
---
- name: Create a Instance
  nvidia.infra_controller.instance:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: present
    name: "my-instance"

- name: Delete a Instance
  nvidia.infra_controller.instance:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: absent
    name: "my-instance"
'''

RETURN = r'''
---
resource:
    description: The resource details.
    type: dict
    returned: when state is present
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import CrudResource


ARGUMENT_SPEC = dict(
always_boot_with_custom_ipxe=dict(type='bool'),
apply_updates_on_reboot=dict(type='bool'),
auto_network=dict(type='bool'),
count=dict(type='int'),
description=dict(type='str'),
dpu_extension_service_deployments=dict(type='list', elements='dict', options=dict(
    dpu_extension_service_id=dict(type='str'),
    version=dict(type='str'),
)),
id=dict(type='str'),
infiniband_interfaces=dict(type='list', elements='dict', options=dict(
    device=dict(type='str'),
    device_instance=dict(type='int'),
    is_physical=dict(type='bool'),
    partition_id=dict(type='str'),
    vendor=dict(type='str'),
    virtual_function_id=dict(type='int'),
)),
instance_id=dict(type='str'),
instance_type_id=dict(type='str'),
interfaces=dict(type='list', elements='dict', options=dict(
    device=dict(type='str'),
    device_instance=dict(type='int'),
    inline_routing_profile=dict(type='str'),
    ip_address=dict(type='str'),
    is_physical=dict(type='bool'),
    subnet_id=dict(type='str'),
    virtual_function_id=dict(type='int'),
    vpc_prefix_id=dict(type='str'),
)),
ipxe_script=dict(type='str'),
is_repair_tenant=dict(type='bool'),
labels=dict(type='dict'),
machine_health_issue=dict(type='dict', options=dict(
    category=dict(type='str', required=True, choices=['Hardware', 'Network', 'Performance', 'Storage', 'Software', 'Other']),
    details=dict(type='str', required=True),
    summary=dict(type='str', required=True),
)),
name=dict(type='str'),
name_prefix=dict(type='str'),
network_security_group_id=dict(type='str'),
nv_link_interfaces=dict(type='list', elements='dict', options=dict(
    device_instance=dict(type='int'),
    nv_linklogical_partition_id=dict(type='str'),
)),
operating_system_id=dict(type='str'),
phone_home_enabled=dict(type='bool'),
reboot_with_custom_ipxe=dict(type='bool'),
secondary_vpc_ids=dict(type='list', elements='str'),
ssh_key_group_ids=dict(type='list', elements='str'),
state=dict(type='str', choices=['present', 'absent']),
tenant_id=dict(type='str'),
topology_optimized=dict(type='bool'),
trigger_reboot=dict(type='bool'),
user_data=dict(type='str'),
vpc_id=dict(type='str'),
wait=dict(type='bool'),
wait_timeout=dict(type='int'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/instance/{instanceId}/nvlink-interface',
    'resource_item_path': '/v2/org/{org}/nico/instance/{instanceId}',
    'id_param': 'instanceId',
    'name_field': 'name',
    'create_schema_fields': ['name_prefix', 'count', 'description', 'tenant_id', 'instance_type_id', 'vpc_id', 'secondary_vpc_ids', 'user_data', 'operating_system_id', 'network_security_group_id', 'ipxe_script', 'always_boot_with_custom_ipxe', 'phone_home_enabled', 'labels', 'interfaces', 'auto_network', 'infiniband_interfaces', 'dpu_extension_service_deployments', 'nv_link_interfaces', 'ssh_key_group_ids', 'topology_optimized'],
    'update_schema_fields': ['name', 'description', 'trigger_reboot', 'reboot_with_custom_ipxe', 'apply_updates_on_reboot', 'operating_system_id', 'ipxe_script', 'ssh_key_group_ids', 'network_security_group_id', 'user_data', 'always_boot_with_custom_ipxe', 'phone_home_enabled', 'labels', 'secondary_vpc_ids', 'interfaces', 'auto_network', 'infiniband_interfaces', 'nv_link_interfaces', 'dpu_extension_service_deployments'],
    'scope_fields': [],
    'ready_statuses': ['Ready'],
    'error_statuses': ['Error'],
    'no_create': False,
    'delete_body_fields': ['machine_health_issue', 'is_repair_tenant'],
    'version_field': None,
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    CrudResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
