#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.instance_type
short_description: Manage Instance Type resources
description:
- Instance Types allow grouping Machines into a pool defined by their capabilities. Providers can then allocate a portion
  of the Instance Type pool to a Tenant.
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  description:
    type: str
    description:
    - Description of the Instance Type
  id:
    type: str
    description:
    - ID of the resource. Used for lookup.
  instance_type_id:
    type: str
    description:
    - 'ID path parameter: instance_type_id.'
  labels:
    type: dict
    description:
    - User-defined key-value labels for the Instance Type
  machine_association_id:
    type: str
    description:
    - 'ID path parameter: machine_association_id.'
  machine_capabilities:
    type: list
    description:
    - List of Machine Capabilities to match
    elements: dict
    suboptions:
      capacity:
        type: str
        description:
        - capacity parameter.
      cores:
        type: int
        description:
        - cores parameter.
      count:
        type: int
        description:
        - count parameter.
      device_type:
        type: str
        description:
        - device_type parameter.
      frequency:
        type: str
        description:
        - frequency parameter.
      hardware_revision:
        type: str
        description:
        - hardware_revision parameter.
      inactive_devices:
        type: list
        description:
        - inactive_devices parameter.
        elements: int
      name:
        type: str
        description:
        - name parameter.
      threads:
        type: int
        description:
        - threads parameter.
      type:
        type: str
        description:
        - type parameter.
        choices:
        - CPU
        - Memory
        - Storage
        - Network
        - GPU
        - InfiniBand
        - DPU
      vendor:
        type: str
        description:
        - vendor parameter.
  machine_ids:
    type: list
    description:
    - ID of the Machine
    elements: str
  name:
    type: str
    description:
    - Name of the Instance Type
  site_id:
    type: str
    description:
    - 'Scope filter: site_id.'
  state:
    type: str
    description:
    - Desired state of the resource.
    choices:
    - present
    - absent
  wait:
    type: bool
    description:
    - Wait for the resource to reach the desired state.
  wait_timeout:
    type: int
    description:
    - Timeout in seconds for wait operations.
'''

EXAMPLES = r'''
---
- name: Create a Instance Type
  nvidia.infra_controller.instance_type:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: present
    name: "my-instance-type"

- name: Delete a Instance Type
  nvidia.infra_controller.instance_type:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: absent
    name: "my-instance-type"
'''

RETURN = r'''
---
resource:
    description: The resource details.
    type: dict
    returned: when state is present
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import CrudResource


ARGUMENT_SPEC = dict(
description=dict(type='str'),
id=dict(type='str'),
instance_type_id=dict(type='str'),
labels=dict(type='dict'),
machine_association_id=dict(type='str'),
machine_capabilities=dict(type='list', elements='dict', options=dict(
    capacity=dict(type='str'),
    cores=dict(type='int'),
    count=dict(type='int'),
    device_type=dict(type='str'),
    frequency=dict(type='str'),
    hardware_revision=dict(type='str'),
    inactive_devices=dict(type='list', elements='int'),
    name=dict(type='str'),
    threads=dict(type='int'),
    type=dict(type='str', choices=['CPU', 'Memory', 'Storage', 'Network', 'GPU', 'InfiniBand', 'DPU']),
    vendor=dict(type='str'),
)),
machine_ids=dict(type='list', elements='str'),
name=dict(type='str'),
site_id=dict(type='str'),
state=dict(type='str', choices=['present', 'absent']),
wait=dict(type='bool'),
wait_timeout=dict(type='int'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/instance/type/{instanceTypeId}/machine',
    'resource_item_path': '/v2/org/{org}/nico/instance/type/{instanceTypeId}/machine/{machineAssociationId}',
    'id_param': 'machineAssociationId',
    'name_field': 'name',
    'create_schema_fields': ['machine_ids'],
    'update_schema_fields': ['name', 'description', 'labels', 'machine_capabilities'],
    'scope_fields': ['site_id'],
    'ready_statuses': ['Ready'],
    'error_statuses': ['Error'],
    'no_create': False,
    'delete_body_fields': [],
    'version_field': None,
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    CrudResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
