#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.machine_validation_info
short_description: Retrieve Machine Validation information
description:
- Machine Validation is the mechanism through which a series of validation tests are executed against a Machine verify its
  integrity. The tests are run for each Machine on ingestion, they can also be run on-demand.
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  machine_id:
    type: str
    description:
    - 'ID path parameter: machine_id.'
'''

EXAMPLES = r'''
---
- name: List all Machine Validation resources
  nvidia.infra_controller.machine_validation_info:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"

- name: Get a specific Machine Validation by ID
  nvidia.infra_controller.machine_validation_info:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    id: "{{ resource_id }}"
'''

RETURN = r'''
---
resources:
    description: List of resources.
    type: list
    returned: when no id is specified
    elements: dict
resource:
    description: Single resource details.
    type: dict
    returned: when id is specified
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import InfoResource


ARGUMENT_SPEC = dict(
machine_id=dict(type='str'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/machine/{machineId}/validation/result',
    'resource_item_path': '',
    'id_param': 'id',
    'filter_fields': [],
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    InfoResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
