#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.measured_boot_trusted_machine
short_description: Manage Measured Boot Trusted Machine resources
description:
- Measured Boot Trusted Machine endpoints manage automatic measurement promotion approvals for Machines at a Site
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  approval_type:
    type: str
    description:
    - Whether the approval is consumed once or persists for future reports.
    choices:
    - Oneshot
    - Persist
  comments:
    type: str
    description:
    - Optional operator comments about the approval.
  id:
    type: str
    description:
    - ID of the resource. Used for lookup.
  machine_id:
    type: str
    description:
    - Machine UUID, or `*` to approve all Machines at the Site.
  pcr_registers:
    type: str
    description:
    - Optional comma-separated PCR register selector. All registers are used when omitted.
  site_id:
    type: str
    description:
    - ID of the Site where the approval applies.
  state:
    type: str
    description:
    - Desired state of the resource.
    choices:
    - present
    - absent
  wait:
    type: bool
    description:
    - Wait for the resource to reach the desired state.
  wait_timeout:
    type: int
    description:
    - Timeout in seconds for wait operations.
'''

EXAMPLES = r'''
---
- name: Create a Measured Boot Trusted Machine
  nvidia.infra_controller.measured_boot_trusted_machine:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: present
    name: "my-measured-boot-trusted-machine"

- name: Delete a Measured Boot Trusted Machine
  nvidia.infra_controller.measured_boot_trusted_machine:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: absent
    name: "my-measured-boot-trusted-machine"
'''

RETURN = r'''
---
resource:
    description: The resource details.
    type: dict
    returned: when state is present
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import CrudResource


ARGUMENT_SPEC = dict(
approval_type=dict(type='str', choices=['Oneshot', 'Persist']),
comments=dict(type='str'),
id=dict(type='str'),
machine_id=dict(type='str'),
pcr_registers=dict(type='str'),
site_id=dict(type='str'),
state=dict(type='str', choices=['present', 'absent']),
wait=dict(type='bool'),
wait_timeout=dict(type='int'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/measured-boot/trusted-machine',
    'resource_item_path': '/v2/org/{org}/nico/measured-boot/trusted-machine/{id}',
    'id_param': 'id',
    'name_field': None,
    'create_schema_fields': ['site_id', 'machine_id', 'approval_type', 'pcr_registers', 'comments'],
    'update_schema_fields': [],
    'scope_fields': [],
    'ready_statuses': ['Ready'],
    'error_statuses': ['Error'],
    'no_create': False,
    'delete_body_fields': [],
    'version_field': None,
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    CrudResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
