#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.operating_system
short_description: Manage Operating System resources
description:
- Operating Systems in NICo are typically iPXE scripts that are used to boot Machines.
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  allow_override:
    type: bool
    description:
    - Indicates if the user data can be overridden at Instance creation time
  deactivation_note:
    type: str
    description:
    - Optional deactivation note if OS is inactive
  description:
    type: str
    description:
    - Optional description of the Operating System
  id:
    type: str
    description:
    - ID of the resource. Used for lookup.
  image_auth_token:
    type: str
    description:
    - Auth token to retrieve the image from image URL, required if imageAuthType is specified
  image_auth_type:
    type: str
    description:
    - Authentication type for image URL, if needed, e.g., basic/bearer/token; required if imageAuthToken is specified
  image_disk:
    type: str
    description:
    - Disk path where the image should be mounted, optional
  image_sha:
    type: str
    description:
    - SHA hash of the image file, required for image-based OS
  image_url:
    type: str
    description:
    - Original URL from which the Operating System image can be retrieved; required for image-based OS. Cannot be specified
      if ipxeScript is specified
  infrastructure_provider_id:
    type: str
    description:
    - 'Deprecated: Infrastructure Provider is now inferred from org membership.'
  ipxe_script:
    type: str
    description:
    - 'Deprecated: raw iPXE Operating Systems are superseded by Templated iPXE (ipxeTemplateId). iPXE script or URL, only
      applicable for iPXE-based OS. Cannot be specified if imageUrl is specified.'
  ipxe_template_artifacts:
    type: list
    description:
    - Artifacts (kernel, initrd, ISO, ...) for the iPXE OS definition (Templated iPXE only).
    elements: dict
    suboptions:
      auth_token:
        type: str
        description:
        - auth_token parameter.
      auth_type:
        type: str
        description:
        - auth_type parameter.
      cache_strategy:
        type: str
        description:
        - cache_strategy parameter.
        choices:
        - CacheAsNeeded
        - LocalOnly
        - CachedOnly
        - RemoteOnly
      name:
        type: str
        description:
        - name parameter.
        required: true
      sha:
        type: str
        description:
        - sha parameter.
      url:
        type: str
        description:
        - url parameter.
        required: true
  ipxe_template_id:
    type: str
    description:
    - ID of the iPXE template to use; identifies a Templated iPXE Operating System. Mutually exclusive with ipxeScript and
      imageUrl.
  ipxe_template_parameters:
    type: list
    description:
    - Parameters passed to the iPXE template (Templated iPXE only).
    elements: dict
    suboptions:
      name:
        type: str
        description:
        - name parameter.
        required: true
      value:
        type: str
        description:
        - value parameter.
        required: true
  is_active:
    type: bool
    description:
    - Indicates if the Operating System is active
  is_cloud_init:
    type: bool
    description:
    - 'Deprecated and ignored: whether the Operating System is cloud-init based. Value now derived from `userData`.'
  name:
    type: str
    description:
    - Name of the Operating System
  operating_system_id:
    type: str
    description:
    - 'ID path parameter: operating_system_id.'
  phone_home_enabled:
    type: bool
    description:
    - Indicates whether the Phone Home service should be enabled or disabled for Operating System
  root_fs_id:
    type: str
    description:
    - Root filesystem UUID; this or `rootFsLabel` is required for image-based OS
  root_fs_label:
    type: str
    description:
    - Root filesystem label; this or `rootFsId` is required for image-based OS
  site_ids:
    type: list
    description:
    - Target Site for the Operating System. For image-based and Templated iPXE Operating Systems exactly one Site is required,
      even though this field is an array. The list is fixed at creation and cannot be changed on update. Not applicable to
      raw iPXE OS.
    elements: str
  state:
    type: str
    description:
    - Desired state of the resource.
    choices:
    - present
    - absent
  tenant_id:
    type: str
    description:
    - 'Deprecated: Tenant is now inferred from org membership.'
  user_data:
    type: str
    description:
    - User data for the Operating System
  wait:
    type: bool
    description:
    - Wait for the resource to reach the desired state.
  wait_timeout:
    type: int
    description:
    - Timeout in seconds for wait operations.
'''

EXAMPLES = r'''
---
- name: Create a Operating System
  nvidia.infra_controller.operating_system:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: present
    name: "my-operating-system"

- name: Delete a Operating System
  nvidia.infra_controller.operating_system:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: absent
    name: "my-operating-system"
'''

RETURN = r'''
---
resource:
    description: The resource details.
    type: dict
    returned: when state is present
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import CrudResource


ARGUMENT_SPEC = dict(
allow_override=dict(type='bool'),
deactivation_note=dict(type='str'),
description=dict(type='str'),
id=dict(type='str'),
image_auth_token=dict(type='str'),
image_auth_type=dict(type='str'),
image_disk=dict(type='str'),
image_sha=dict(type='str'),
image_url=dict(type='str'),
infrastructure_provider_id=dict(type='str'),
ipxe_script=dict(type='str'),
ipxe_template_artifacts=dict(type='list', elements='dict', options=dict(
    auth_token=dict(type='str'),
    auth_type=dict(type='str'),
    cache_strategy=dict(type='str', choices=['CacheAsNeeded', 'LocalOnly', 'CachedOnly', 'RemoteOnly']),
    name=dict(type='str', required=True),
    sha=dict(type='str'),
    url=dict(type='str', required=True),
)),
ipxe_template_id=dict(type='str'),
ipxe_template_parameters=dict(type='list', elements='dict', options=dict(
    name=dict(type='str', required=True),
    value=dict(type='str', required=True),
)),
is_active=dict(type='bool'),
is_cloud_init=dict(type='bool'),
name=dict(type='str'),
operating_system_id=dict(type='str'),
phone_home_enabled=dict(type='bool'),
root_fs_id=dict(type='str'),
root_fs_label=dict(type='str'),
site_ids=dict(type='list', elements='str'),
state=dict(type='str', choices=['present', 'absent']),
tenant_id=dict(type='str'),
user_data=dict(type='str'),
wait=dict(type='bool'),
wait_timeout=dict(type='int'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/operating-system',
    'resource_item_path': '/v2/org/{org}/nico/operating-system/{operatingSystemId}',
    'id_param': 'operatingSystemId',
    'name_field': 'name',
    'create_schema_fields': ['name', 'description', 'infrastructure_provider_id', 'tenant_id', 'site_ids', 'ipxe_script', 'image_url', 'image_sha', 'image_auth_type', 'image_auth_token', 'image_disk', 'root_fs_id', 'root_fs_label', 'phone_home_enabled', 'user_data', 'is_cloud_init', 'allow_override', 'ipxe_template_id', 'ipxe_template_parameters', 'ipxe_template_artifacts'],
    'update_schema_fields': ['name', 'description', 'ipxe_script', 'image_url', 'image_sha', 'image_auth_type', 'image_auth_token', 'image_disk', 'root_fs_id', 'root_fs_label', 'phone_home_enabled', 'user_data', 'is_cloud_init', 'allow_override', 'is_active', 'deactivation_note', 'ipxe_template_id', 'ipxe_template_parameters', 'ipxe_template_artifacts'],
    'scope_fields': [],
    'ready_statuses': ['Ready'],
    'error_statuses': ['Error'],
    'no_create': False,
    'delete_body_fields': [],
    'version_field': None,
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    CrudResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
