#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.rack_info
short_description: Retrieve Rack information
description:
- Rack is a physical enclosure that contains a number of Machines. Racks are the physical building blocks of a Site.
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  active_only:
    type: bool
    description:
    - Restrict results to non-terminal Tasks.
  id:
    type: str
    description:
    - ID of the resource to retrieve.
  include_components:
    type: bool
    description:
    - Include rack components in response
  include_report:
    type: bool
    description:
    - Include the per-task execution report on each returned task.
  manufacturer:
    type: str
    description:
    - Filter racks by manufacturer
  name:
    type: str
    description:
    - Filter racks by name
  site_id:
    type: str
    description:
    - ID of the Site that owns the Rack.
'''

EXAMPLES = r'''
---
- name: List all Rack resources
  nvidia.infra_controller.rack_info:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"

- name: Get a specific Rack by ID
  nvidia.infra_controller.rack_info:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    id: "{{ resource_id }}"
'''

RETURN = r'''
---
resources:
    description: List of resources.
    type: list
    returned: when no id is specified
    elements: dict
resource:
    description: Single resource details.
    type: dict
    returned: when id is specified
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import InfoResource


ARGUMENT_SPEC = dict(
active_only=dict(type='bool'),
id=dict(type='str'),
include_components=dict(type='bool'),
include_report=dict(type='bool'),
manufacturer=dict(type='str'),
name=dict(type='str'),
site_id=dict(type='str'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/rack/{id}/task',
    'resource_item_path': '/v2/org/{org}/nico/rack/{id}',
    'id_param': 'id',
    'filter_fields': ['site_id', 'include_components', 'name', 'manufacturer', 'site_id', 'name', 'manufacturer', 'site_id', 'site_id', 'active_only', 'include_report'],
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    InfoResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
