#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.rack_firmware
short_description: Manage Rack resources
description:
- Rack is a physical enclosure that contains a number of Machines. Racks are the physical building blocks of a Site.
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  filter:
    type: dict
    description:
    - Filter criteria for selecting racks in batch operations. If omitted or empty, all racks in the site are targeted.
    suboptions:
      names:
        type: list
        description:
        - names parameter.
        elements: str
  id:
    type: str
    description:
    - ID of the resource. When provided, targets a single resource.
  site_id:
    type: str
    description:
    - ID of the Site
  targets:
    type: list
    description:
    - "Optional subset of firmware targets to update within the targeted tray.\nNames are lowercase and select sub-parts of\
      \ the tray\n(BMC, BIOS, etc.). The accepted set per tray type comes from\nthe Flow service's NICo proto bindings (which\
      \ mirror Core's\nper-tray-type enums in `NICo-core/crates/rpc/proto/forge.proto`),\nso the supported values track Core\
      \ as new sub-parts are added:\n  - switch trays (NvSwitchComponent): currently bmc, cpld, bios, nvos\n  - powershelf\
      \ trays (PowerShelfComponent): currently pmc, psu\n  - compute trays (ComputeTrayComponent): currently bmc, bios\n \
      \   (currently NOT honored end-to-end: the NICo compute-firmware\n    path goes through SetFirmwareUpdateTimeWindow\
      \ + auto-update,\n    which has no per-target selection; the request is logged\n    and the whole bundle is applied.\
      \ Will be honored once\n    compute moves to UpdateComponentFirmware.)\nOmitted or empty means \"update everything in\
      \ the bundle\"\n(the historical default). Unknown names are rejected.\nRequires `version` to be set."
    elements: str
  version:
    type: str
    description:
    - Target firmware version.
'''

EXAMPLES = r'''
---
- name: Run firmware on all rack resources
  nvidia.infra_controller.rack_firmware:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"

- name: Run firmware on a specific rack
  nvidia.infra_controller.rack_firmware:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    id: "{{ resource_id }}"
'''

RETURN = r'''
---
result:
    description: The action result.
    type: dict
    returned: always
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import ActionResource


ARGUMENT_SPEC = dict(
filter=dict(type='dict', options=dict(
    names=dict(type='list', elements='str'),
)),
id=dict(type='str'),
site_id=dict(type='str'),
targets=dict(type='list', elements='str'),
version=dict(type='str'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/carbide/rack/firmware',
    'resource_item_path': '/v2/org/{org}/carbide/rack/{id}/firmware',
    'method': 'PATCH',
    'body_fields': ['site_id', 'version', 'targets', 'filter'],
    'query_fields': [],
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    ActionResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
