#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.rule_info
short_description: Retrieve Rule information
description:
- 'Operation Rule defines, per Site, how a particular operation (for example `PowerControl` / `power_on` or `FirmwareControl`
  / `upgrade`) should be executed against a set of components: ordered execution stages, per-component-type concurrency, pre
  / main / post actions, timeouts, and retry policy. Rules are reusable templates owned by Flow; this tag exposes CRUD (`POST`,
  `GET`, `PATCH`, `DELETE`) over them.'
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  id:
    type: str
    description:
    - ID of the resource to retrieve.
  operation_type:
    type: str
    description:
    - Filter by operation type.
    choices:
    - PowerControl
    - FirmwareControl
  site_id:
    type: str
    description:
    - ID of the Site that owns the rules (rules are site-scoped).
'''

EXAMPLES = r'''
---
- name: List all Rule resources
  nvidia.infra_controller.rule_info:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"

- name: Get a specific Rule by ID
  nvidia.infra_controller.rule_info:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    id: "{{ resource_id }}"
'''

RETURN = r'''
---
resources:
    description: List of resources.
    type: list
    returned: when no id is specified
    elements: dict
resource:
    description: Single resource details.
    type: dict
    returned: when id is specified
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import InfoResource


ARGUMENT_SPEC = dict(
id=dict(type='str'),
operation_type=dict(type='str', choices=['PowerControl', 'FirmwareControl']),
site_id=dict(type='str'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/task/rule',
    'resource_item_path': '/v2/org/{org}/nico/task/rule/{id}',
    'id_param': 'id',
    'filter_fields': ['site_id', 'operation_type'],
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    InfoResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
