#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.rule
short_description: Manage Rule resources
description:
- 'Operation Rule defines, per Site, how a particular operation (for example `PowerControl` / `power_on` or `FirmwareControl`
  / `upgrade`) should be executed against a set of components: ordered execution stages, per-component-type concurrency, pre
  / main / post actions, timeouts, and retry policy. Rules are reusable templates owned by Flow; this tag exposes CRUD (`POST`,
  `GET`, `PATCH`, `DELETE`) over them.'
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  description:
    type: str
    description:
    - Optional free-form description.
  id:
    type: str
    description:
    - ID of the resource. Used for lookup.
  name:
    type: str
    description:
    - Human-readable name of the rule.
  operation_code:
    type: str
    description:
    - Operation code within the operation type (e.g. `power_on`).
  operation_type:
    type: str
    description:
    - Operation type the rule applies to.
    choices:
    - PowerControl
    - FirmwareControl
  rule_definition:
    type: dict
    description:
    - 'Executable definition of a rule. Mirrors Flow''s wire schema 1:1 so existing

      YAML rule files can be converted to JSON without any key renaming

      (nested fields use `snake_case`).'
    suboptions:
      steps:
        type: list
        description:
        - steps parameter.
        elements: dict
      version:
        type: str
        description:
        - version parameter.
        required: true
        choices:
        - v1
  site_id:
    type: str
    description:
    - ID of the Site to create the rule on.
  state:
    type: str
    description:
    - Desired state of the resource.
    choices:
    - present
    - absent
  wait:
    type: bool
    description:
    - Wait for the resource to reach the desired state.
  wait_timeout:
    type: int
    description:
    - Timeout in seconds for wait operations.
'''

EXAMPLES = r'''
---
- name: Create a Rule
  nvidia.infra_controller.rule:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: present
    name: "my-rule"

- name: Delete a Rule
  nvidia.infra_controller.rule:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: absent
    name: "my-rule"
'''

RETURN = r'''
---
resource:
    description: The resource details.
    type: dict
    returned: when state is present
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import CrudResource


ARGUMENT_SPEC = dict(
description=dict(type='str'),
id=dict(type='str'),
name=dict(type='str'),
operation_code=dict(type='str'),
operation_type=dict(type='str', choices=['PowerControl', 'FirmwareControl']),
rule_definition=dict(type='dict', options=dict(
    steps=dict(type='list', elements='dict', options=dict(
        component_type=dict(type='str', required=True),
        delay_after=dict(type='str'),
        main_operation=dict(type='dict', required=True, options=dict(
            name=dict(type='str', required=True, choices=['Sleep', 'PowerControl', 'VerifyPowerStatus', 'VerifyReachability', 'GetPowerStatus', 'FirmwareControl', 'VerifyFirmwareVersion', 'VerifyFirmwareConsistency', 'BringUpControl', 'WaitBringUp', 'InjectExpectation']),
            parameters=dict(type='dict'),
            poll_interval=dict(type='str'),
            timeout=dict(type='str'),
        )),
        max_parallel=dict(type='int'),
        post_operation=dict(type='list', elements='dict', options=dict(
            name=dict(type='str', required=True, choices=['Sleep', 'PowerControl', 'VerifyPowerStatus', 'VerifyReachability', 'GetPowerStatus', 'FirmwareControl', 'VerifyFirmwareVersion', 'VerifyFirmwareConsistency', 'BringUpControl', 'WaitBringUp', 'InjectExpectation']),
            parameters=dict(type='dict'),
            poll_interval=dict(type='str'),
            timeout=dict(type='str'),
        )),
        pre_operation=dict(type='list', elements='dict', options=dict(
            name=dict(type='str', required=True, choices=['Sleep', 'PowerControl', 'VerifyPowerStatus', 'VerifyReachability', 'GetPowerStatus', 'FirmwareControl', 'VerifyFirmwareVersion', 'VerifyFirmwareConsistency', 'BringUpControl', 'WaitBringUp', 'InjectExpectation']),
            parameters=dict(type='dict'),
            poll_interval=dict(type='str'),
            timeout=dict(type='str'),
        )),
        retry=dict(type='dict', options=dict(
            backoff_coefficient=dict(type='float', required=True),
            initial_interval=dict(type='str', required=True),
            max_attempts=dict(type='int', required=True),
            max_interval=dict(type='str'),
        )),
        stage=dict(type='int', required=True),
        timeout=dict(type='str'),
    )),
    version=dict(type='str', required=True, choices=['v1']),
)),
site_id=dict(type='str'),
state=dict(type='str', choices=['present', 'absent']),
wait=dict(type='bool'),
wait_timeout=dict(type='int'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/task/rule',
    'resource_item_path': '/v2/org/{org}/nico/task/rule/{id}',
    'id_param': 'id',
    'name_field': 'name',
    'create_schema_fields': ['site_id', 'name', 'description', 'operation_type', 'operation_code', 'rule_definition'],
    'update_schema_fields': ['site_id', 'name', 'description', 'rule_definition'],
    'scope_fields': [],
    'ready_statuses': ['Ready'],
    'error_statuses': ['Error'],
    'no_create': False,
    'delete_body_fields': [],
    'version_field': None,
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    CrudResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
