#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.site_info
short_description: Retrieve Site information
description:
- Site is a datacenter that contains physical hardware and networking resources. All resources created by Provider or Tenant
  are directly or indirectly anchored to the Site object.
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  id:
    type: str
    description:
    - ID of the resource to retrieve.
  include_machine_stats:
    type: bool
    description:
    - Include a breakdown of Machine counts by life-cycle status and health. Requires Provider Admin role.
  infrastructure_provider_id:
    type: str
    description:
    - Filter Sites by Infrastructure Provider ID
  is_flow_enabled:
    type: bool
    description:
    - Filter Sites by NICo Flow enabled flag. Requires Provider Admin role.
  is_native_networking_enabled:
    type: bool
    description:
    - Filter Sites by native networking enabled flag. Requires Provider Admin role.
  is_network_security_group_enabled:
    type: bool
    description:
    - Filter Sites by network security group enabled flag. Requires Provider Admin role.
  is_nv_link_partition_enabled:
    type: bool
    description:
    - Filter Sites by NVLink partitioning enabled flag. Requires Provider Admin role.
  query:
    type: str
    description:
    - Search for matches across all Sites. Input will be matched against name, description, location, contact, and status
      fields
  site_id:
    type: str
    description:
    - 'ID path parameter: site_id.'
  status:
    type: str
    description:
    - Filter Sites by Status. Can be specified multiple times to filter on more than one status
  tenant_id:
    type: str
    description:
    - Filter Sites by Tenant ID
'''

EXAMPLES = r'''
---
- name: List all Site resources
  nvidia.infra_controller.site_info:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"

- name: Get a specific Site by ID
  nvidia.infra_controller.site_info:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    id: "{{ resource_id }}"
'''

RETURN = r'''
---
resources:
    description: List of resources.
    type: list
    returned: when no id is specified
    elements: dict
resource:
    description: Single resource details.
    type: dict
    returned: when id is specified
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import InfoResource


ARGUMENT_SPEC = dict(
id=dict(type='str'),
include_machine_stats=dict(type='bool'),
infrastructure_provider_id=dict(type='str'),
is_flow_enabled=dict(type='bool'),
is_native_networking_enabled=dict(type='bool'),
is_network_security_group_enabled=dict(type='bool'),
is_nv_link_partition_enabled=dict(type='bool'),
query=dict(type='str'),
site_id=dict(type='str'),
status=dict(type='str'),
tenant_id=dict(type='str'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/site/{siteId}/status-history',
    'resource_item_path': '/v2/org/{org}/nico/site/{siteId}',
    'id_param': 'siteId',
    'filter_fields': ['infrastructure_provider_id', 'tenant_id', 'status', 'is_native_networking_enabled', 'is_network_security_group_enabled', 'is_nv_link_partition_enabled', 'is_flow_enabled', 'include_machine_stats', 'query'],
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    InfoResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
