#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.site_explorer
short_description: Manage Site Explorer resources
description:
- Site Explorer discovers BMC endpoints on a Site and tracks their exploration state.
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  action:
    type: str
    description:
    - Site Explorer endpoint action to trigger.
    choices:
    - ClearError
    - ReExplore
  endpoint_ids:
    type: list
    description:
    - BMC IP addresses to target when target is EndpointIds.
    elements: str
  id:
    type: str
    description:
    - ID of the resource. Used for lookup.
  site_id:
    type: str
    description:
    - ID of the Site whose explored endpoints are targeted.
  state:
    type: str
    description:
    - Desired state of the resource.
    choices:
    - present
    - absent
  target:
    type: str
    description:
    - Endpoint set to target.
    choices:
    - All
    - EndpointIds
  wait:
    type: bool
    description:
    - Wait for the resource to reach the desired state.
  wait_timeout:
    type: int
    description:
    - Timeout in seconds for wait operations.
'''

EXAMPLES = r'''
---
- name: Create a Site Explorer
  nvidia.infra_controller.site_explorer:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: present
    name: "my-site-explorer"

- name: Delete a Site Explorer
  nvidia.infra_controller.site_explorer:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: absent
    name: "my-site-explorer"
'''

RETURN = r'''
---
resource:
    description: The resource details.
    type: dict
    returned: when state is present
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import CrudResource


ARGUMENT_SPEC = dict(
action=dict(type='str', choices=['ClearError', 'ReExplore']),
endpoint_ids=dict(type='list', elements='str'),
id=dict(type='str'),
site_id=dict(type='str'),
state=dict(type='str', choices=['present', 'absent']),
target=dict(type='str', choices=['All', 'EndpointIds']),
wait=dict(type='bool'),
wait_timeout=dict(type='int'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/site-explorer/endpoint/action',
    'resource_item_path': '',
    'id_param': 'id',
    'name_field': None,
    'create_schema_fields': ['site_id', 'action', 'target', 'endpoint_ids'],
    'update_schema_fields': [],
    'scope_fields': [],
    'ready_statuses': ['Ready'],
    'error_statuses': ['Error'],
    'no_create': False,
    'delete_body_fields': [],
    'version_field': None,
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    CrudResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
