#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.task_run
short_description: Manage Task Run resources
description:
- A Task Run is a phased, policy-gated execution of one operation (currently firmware) across many Racks. A Task Run narrows
  a candidate set of Racks with an optional selector, divides the selected Racks into phases, and drives one execution target
  per Rack; each target in turn drives at most one Task. Safety gates pause the Task Run when failures exceed a threshold,
  and phase gates hold each phase until an operator advances it. This tag exposes creation, retrieval, target listing, and
  the pause / resume / advance / cancel lifecycle actions; drill into per-Rack execution detail via the Task tag using each
  target's `taskId`.
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  id:
    type: str
    description:
    - ID of the resource. Used for lookup.
  reason:
    type: str
    description:
    - Optional free-form reason recorded with the cancellation.
  site_id:
    type: str
    description:
    - ID of the Site that owns the Task Run.
  state:
    type: str
    description:
    - Desired state of the resource.
    choices:
    - present
    - absent
  wait:
    type: bool
    description:
    - Wait for the resource to reach the desired state.
  wait_timeout:
    type: int
    description:
    - Timeout in seconds for wait operations.
'''

EXAMPLES = r'''
---
- name: Create a Task Run
  nvidia.infra_controller.task_run:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: present
    name: "my-task-run"

- name: Delete a Task Run
  nvidia.infra_controller.task_run:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: absent
    name: "my-task-run"
'''

RETURN = r'''
---
resource:
    description: The resource details.
    type: dict
    returned: when state is present
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import CrudResource


ARGUMENT_SPEC = dict(
id=dict(type='str'),
reason=dict(type='str'),
site_id=dict(type='str'),
state=dict(type='str', choices=['present', 'absent']),
wait=dict(type='bool'),
wait_timeout=dict(type='int'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/task/run/{id}/cancel',
    'resource_item_path': '/v2/org/{org}/nico/task/run/{id}',
    'id_param': 'id',
    'name_field': None,
    'create_schema_fields': ['site_id', 'reason'],
    'update_schema_fields': [],
    'scope_fields': [],
    'ready_statuses': ['Ready'],
    'error_statuses': ['Error'],
    'no_create': False,
    'delete_body_fields': [],
    'version_field': None,
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    CrudResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
