#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.task
short_description: Manage Task resources
description:
- Task represents an asynchronous, site-scoped operation (for example firmware update, power state change, or rack bring-up).
  Tasks are created when operations run against Racks, Trays, or other components. Endpoints in this tag retrieve or cancel
  a Task by ID; list Tasks for a Rack or Tray under the Rack and Tray tags.
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  id:
    type: str
    description:
    - ID of the resource. Used for lookup.
  site_id:
    type: str
    description:
    - ID of the Site that owns the task (tasks are site-scoped).
  state:
    type: str
    description:
    - Desired state of the resource.
    choices:
    - present
    - absent
  wait:
    type: bool
    description:
    - Wait for the resource to reach the desired state.
  wait_timeout:
    type: int
    description:
    - Timeout in seconds for wait operations.
'''

EXAMPLES = r'''
---
- name: Create a Task
  nvidia.infra_controller.task:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: present
    name: "my-task"

- name: Delete a Task
  nvidia.infra_controller.task:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: absent
    name: "my-task"
'''

RETURN = r'''
---
resource:
    description: The resource details.
    type: dict
    returned: when state is present
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import CrudResource


ARGUMENT_SPEC = dict(
id=dict(type='str'),
site_id=dict(type='str'),
state=dict(type='str', choices=['present', 'absent']),
wait=dict(type='bool'),
wait_timeout=dict(type='int'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/task/{id}/cancel',
    'resource_item_path': '/v2/org/{org}/nico/task/{id}',
    'id_param': 'id',
    'name_field': None,
    'create_schema_fields': ['site_id'],
    'update_schema_fields': [],
    'scope_fields': [],
    'ready_statuses': ['Ready'],
    'error_statuses': ['Error'],
    'no_create': False,
    'delete_body_fields': [],
    'version_field': None,
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    CrudResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
