#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.task_run_info
short_description: Retrieve Task Run information
description:
- A Task Run is a phased, policy-gated execution of one operation (currently firmware) across many Racks. A Task Run narrows
  a candidate set of Racks with an optional selector, divides the selected Racks into phases, and drives one execution target
  per Rack; each target in turn drives at most one Task. Safety gates pause the Task Run when failures exceed a threshold,
  and phase gates hold each phase until an operator advances it. This tag exposes creation, retrieval, target listing, and
  the pause / resume / advance / cancel lifecycle actions; drill into per-Rack execution detail via the Task tag using each
  target's `taskId`.
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  id:
    type: str
    description:
    - ID of the resource to retrieve.
  operation_type:
    type: str
    description:
    - Filter by operation type.
    choices:
    - PowerControl
    - FirmwareControl
  phase_scope:
    type: str
    description:
    - Restrict targets to the current phase, completed phases, or both.
    choices:
    - currentPhase
    - completedPhases
    - currentAndCompletedPhases
  site_id:
    type: str
    description:
    - ID of the Site that owns the Task Run.
  status:
    type: str
    description:
    - Filter by target status.
    choices:
    - Pending
    - Blocked
    - Submitted
    - Completed
    - Failed
    - Terminated
    - Skipped
    - Claimed
'''

EXAMPLES = r'''
---
- name: List all Task Run resources
  nvidia.infra_controller.task_run_info:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"

- name: Get a specific Task Run by ID
  nvidia.infra_controller.task_run_info:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    id: "{{ resource_id }}"
'''

RETURN = r'''
---
resources:
    description: List of resources.
    type: list
    returned: when no id is specified
    elements: dict
resource:
    description: Single resource details.
    type: dict
    returned: when id is specified
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import InfoResource


ARGUMENT_SPEC = dict(
id=dict(type='str'),
operation_type=dict(type='str', choices=['PowerControl', 'FirmwareControl']),
phase_scope=dict(type='str', choices=['currentPhase', 'completedPhases', 'currentAndCompletedPhases']),
site_id=dict(type='str'),
status=dict(type='str', choices=['Pending', 'Blocked', 'Submitted', 'Completed', 'Failed', 'Terminated', 'Skipped', 'Claimed']),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/task/run/{id}/cancel',
    'resource_item_path': '/v2/org/{org}/nico/task/run/{id}',
    'id_param': 'id',
    'filter_fields': ['site_id', 'status', 'operation_type', 'site_id', 'status', 'phase_scope'],
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    InfoResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
