#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.tenant_account
short_description: Manage Tenant Account resources
description:
- Tenant Account connects a Tenant with an Infrastructure Provider. It represents/contains any information pertaining to their
  relationship.
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  account_id:
    type: str
    description:
    - 'ID path parameter: account_id.'
  id:
    type: str
    description:
    - ID of the resource. Used for lookup.
  infrastructure_provider_id:
    type: str
    description:
    - "Deprecated; inferred from the caller's org Infrastructure Provider\nwhen omitted. When provided, the value must match\
      \ the org's\nInfrastructure Provider \u2014 mismatched values are rejected with 400."
  site_capabilities:
    type: list
    description:
    - 'Provider Admin replace payload for TargetedInstanceCreation configuration. Required to be non-empty when sent.


      PATCH uses replace semantics: previously configured per-site overrides whose siteId is omitted from the new payload
      are cleared.


      Server validation rules:

      - must contain at least one entry

      - must contain exactly one entry with omitted or empty siteIds

      - must not repeat any siteId across entries

      - every provided siteId must be a valid Site UUID

      - every provided siteId must identify a Site associated with the Tenant and owned by the Tenant Account''s Infrastructure
      Provider; otherwise the server rejects the request with 400'
    elements: dict
    suboptions:
      site_ids:
        type: list
        description:
        - site_ids parameter.
        elements: str
      targeted_instance_creation:
        type: bool
        description:
        - targeted_instance_creation parameter.
        required: true
  state:
    type: str
    description:
    - Desired state of the resource.
    choices:
    - present
    - absent
  tenant_contact_id:
    type: str
    description:
    - Tenant Admin invite acceptance; must match the requesting user
  tenant_org:
    type: str
    description:
    - Must be a valid Org name
  wait:
    type: bool
    description:
    - Wait for the resource to reach the desired state.
  wait_timeout:
    type: int
    description:
    - Timeout in seconds for wait operations.
'''

EXAMPLES = r'''
---
- name: Create a Tenant Account
  nvidia.infra_controller.tenant_account:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: present
    name: "my-tenant-account"

- name: Delete a Tenant Account
  nvidia.infra_controller.tenant_account:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: absent
    name: "my-tenant-account"
'''

RETURN = r'''
---
resource:
    description: The resource details.
    type: dict
    returned: when state is present
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import CrudResource


ARGUMENT_SPEC = dict(
account_id=dict(type='str'),
id=dict(type='str'),
infrastructure_provider_id=dict(type='str'),
site_capabilities=dict(type='list', elements='dict', options=dict(
    site_ids=dict(type='list', elements='str'),
    targeted_instance_creation=dict(type='bool', required=True),
)),
state=dict(type='str', choices=['present', 'absent']),
tenant_contact_id=dict(type='str'),
tenant_org=dict(type='str'),
wait=dict(type='bool'),
wait_timeout=dict(type='int'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/tenant/account',
    'resource_item_path': '/v2/org/{org}/nico/tenant/account/{accountId}',
    'id_param': 'accountId',
    'name_field': None,
    'create_schema_fields': ['infrastructure_provider_id', 'tenant_org'],
    'update_schema_fields': ['tenant_contact_id', 'site_capabilities'],
    'scope_fields': [],
    'ready_statuses': ['Ready'],
    'error_statuses': ['Error'],
    'no_create': False,
    'delete_body_fields': [],
    'version_field': None,
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    CrudResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
