#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.tray_power
short_description: Manage Tray resources
description:
- Tray represents a component within a Rack.
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  filter:
    type: dict
    description:
    - Filter that selects Trays whose power state should be updated
    suboptions:
      component_ids:
        type: list
        description:
        - component_ids parameter.
        elements: str
      ids:
        type: list
        description:
        - ids parameter.
        elements: str
      rack_id:
        type: str
        description:
        - rack_id parameter.
      rack_name:
        type: str
        description:
        - rack_name parameter.
      slot_id:
        type: int
        description:
        - slot_id parameter.
      type:
        type: str
        description:
        - type parameter.
        choices:
        - Compute
        - NVSwitch
        - PowerShelf
  id:
    type: str
    description:
    - ID of the resource. When provided, targets a single resource.
  override_readiness_check:
    type: bool
    description:
    - 'When true, proceed even if one or more target components (or hosts

      on the owning rack for rack-scoped components) are reported as not

      ready by their persisted status. Intended for operator-supervised

      maintenance.'
  rule_id:
    type: str
    description:
    - 'Optional Operation Rule UUID. When set, pins this operation to the

      named rule and overrides Flow''s default rule resolution.'
  site_id:
    type: str
    description:
    - ID of the Site
  state:
    type: str
    description:
    - 'Power control state to apply:

      - `on`: Power on the target(s)

      - `off`: Graceful power off

      - `cycle`: Graceful power cycle (restart)

      - `forceoff`: Forced power off (immediate)

      - `forcecycle`: Forced power cycle (immediate restart)'
    choices:
    - 'on'
    - 'off'
    - cycle
    - forceoff
    - forcecycle
'''

EXAMPLES = r'''
---
- name: Run power on all tray resources
  nvidia.infra_controller.tray_power:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"

- name: Run power on a specific tray
  nvidia.infra_controller.tray_power:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    id: "{{ resource_id }}"
'''

RETURN = r'''
---
result:
    description: The action result.
    type: dict
    returned: always
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import ActionResource


ARGUMENT_SPEC = dict(
filter=dict(type='dict', options=dict(
    component_ids=dict(type='list', elements='str'),
    ids=dict(type='list', elements='str'),
    rack_id=dict(type='str'),
    rack_name=dict(type='str'),
    slot_id=dict(type='int'),
    type=dict(type='str', choices=['Compute', 'NVSwitch', 'PowerShelf']),
)),
id=dict(type='str'),
override_readiness_check=dict(type='bool'),
rule_id=dict(type='str'),
site_id=dict(type='str'),
state=dict(type='str', choices=['on', 'off', 'cycle', 'forceoff', 'forcecycle']),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/carbide/tray/power',
    'resource_item_path': '/v2/org/{org}/carbide/tray/{id}/power',
    'method': 'PATCH',
    'body_fields': ['site_id', 'state', 'rule_id', 'override_readiness_check', 'filter'],
    'query_fields': [],
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    ActionResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
