#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.tray_firmware
short_description: Manage Tray resources
description:
- Tray represents a component within a Rack.
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  filter:
    type: dict
    description:
    - Filter that selects Trays targeted for firmware update
    suboptions:
      component_ids:
        type: list
        description:
        - component_ids parameter.
        elements: str
      ids:
        type: list
        description:
        - ids parameter.
        elements: str
      rack_id:
        type: str
        description:
        - rack_id parameter.
      rack_name:
        type: str
        description:
        - rack_name parameter.
      slot_id:
        type: int
        description:
        - slot_id parameter.
      type:
        type: str
        description:
        - type parameter.
        choices:
        - Compute
        - NVSwitch
        - PowerShelf
  id:
    type: str
    description:
    - ID of the resource. When provided, targets a single resource.
  override_readiness_check:
    type: bool
    description:
    - 'When true, proceed even if one or more target components (or hosts

      on the owning rack for rack-scoped components) are reported as not

      ready by their persisted status. Intended for operator-supervised

      maintenance.'
  rule_id:
    type: str
    description:
    - 'Optional Operation Rule UUID. When set, pins this firmware update to

      the named rule and overrides Flow''s default rule resolution.'
  site_id:
    type: str
    description:
    - ID of the Site
  targets:
    type: list
    description:
    - "Optional subset of firmware targets to update within the targeted tray.\nNames are lowercase and select sub-parts of\
      \ the tray\n(BMC, BIOS, etc.). The accepted set per tray type comes from\nthe Flow service's NICo proto bindings (which\
      \ mirror Core's\nper-tray-type enums in `NICo-core/crates/rpc/proto/forge.proto`),\nso the supported values track Core\
      \ as new sub-parts are added:\n  - switch trays (NvSwitchComponent): currently bmc, cpld, bios, nvos\n  - powershelf\
      \ trays (PowerShelfComponent): currently pmc, psu\n  - compute trays (ComputeTrayComponent): currently bmc, bios\n \
      \   (currently NOT honored end-to-end: the NICo compute-firmware\n    path goes through SetFirmwareUpdateTimeWindow\
      \ + auto-update,\n    which has no per-target selection; the request is logged\n    and the whole bundle is applied.\
      \ Will be honored once\n    compute moves to UpdateComponentFirmware.)\nOmitted or empty means \"update everything in\
      \ the bundle\"\n(the historical default) for compute-tray-internal targets.\nUnknown names are rejected. Requires `version`\
      \ to be set.\nThe special target `dpu`, valid only on compute trays,\nrequests DPU reprovisioning on the matched host.\
      \ Unlike\nthe other targets, `dpu` is NOT covered by the\n\"omitted/empty means everything\" default \u2014 it must\
      \ be\nlisted explicitly. `version` is ignored on the `dpu`\nbranch; the target firmware version comes from site\nconfiguration."
    elements: str
  version:
    type: str
    description:
    - Target firmware version.
'''

EXAMPLES = r'''
---
- name: Run firmware on all tray resources
  nvidia.infra_controller.tray_firmware:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"

- name: Run firmware on a specific tray
  nvidia.infra_controller.tray_firmware:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    id: "{{ resource_id }}"
'''

RETURN = r'''
---
result:
    description: The action result.
    type: dict
    returned: always
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import ActionResource


ARGUMENT_SPEC = dict(
filter=dict(type='dict', options=dict(
    component_ids=dict(type='list', elements='str'),
    ids=dict(type='list', elements='str'),
    rack_id=dict(type='str'),
    rack_name=dict(type='str'),
    slot_id=dict(type='int'),
    type=dict(type='str', choices=['Compute', 'NVSwitch', 'PowerShelf']),
)),
id=dict(type='str'),
override_readiness_check=dict(type='bool'),
rule_id=dict(type='str'),
site_id=dict(type='str'),
targets=dict(type='list', elements='str'),
version=dict(type='str'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/carbide/tray/firmware',
    'resource_item_path': '/v2/org/{org}/carbide/tray/{id}/firmware',
    'method': 'PATCH',
    'body_fields': ['site_id', 'version', 'targets', 'rule_id', 'override_readiness_check', 'filter'],
    'query_fields': [],
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    ActionResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
