#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.tray_firmware
short_description: Manage Tray resources
description:
- Tray represents a component within a Rack.
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  filter:
    type: dict
    description:
    - 'Filter criteria for selecting trays in batch operations. If omitted or empty, all trays in the site are targeted.


      Constraints: `rackId` and `rackName` are mutually exclusive. `rackId`/`rackName` cannot be combined with `ids`/`componentIds`.
      `componentIds` requires `type`. `slotId` requires `rackId` or `rackName`, must be >= 0, and composes with the rest of
      the filter via AND.'
    suboptions:
      component_ids:
        type: list
        description:
        - component_ids parameter.
        elements: str
      ids:
        type: list
        description:
        - ids parameter.
        elements: str
      rack_id:
        type: str
        description:
        - rack_id parameter.
      rack_name:
        type: str
        description:
        - rack_name parameter.
      slot_id:
        type: int
        description:
        - slot_id parameter.
      type:
        type: str
        description:
        - type parameter.
        choices:
        - compute
        - switch
        - powershelf
  id:
    type: str
    description:
    - ID of the resource. When provided, targets a single resource.
  site_id:
    type: str
    description:
    - ID of the Site
  targets:
    type: list
    description:
    - "Optional subset of firmware targets to update within the targeted tray.\nNames are lowercase and select sub-parts of\
      \ the tray\n(BMC, BIOS, etc.). The accepted set per tray type comes from\nthe Flow service's NICo proto bindings (which\
      \ mirror Core's\nper-tray-type enums in `NICo-core/crates/rpc/proto/forge.proto`),\nso the supported values track Core\
      \ as new sub-parts are added:\n  - switch trays (NvSwitchComponent): currently bmc, cpld, bios, nvos\n  - powershelf\
      \ trays (PowerShelfComponent): currently pmc, psu\n  - compute trays (ComputeTrayComponent): currently bmc, bios\n \
      \   (currently NOT honored end-to-end: the NICo compute-firmware\n    path goes through SetFirmwareUpdateTimeWindow\
      \ + auto-update,\n    which has no per-target selection; the request is logged\n    and the whole bundle is applied.\
      \ Will be honored once\n    compute moves to UpdateComponentFirmware.)\nOmitted or empty means \"update everything in\
      \ the bundle\"\n(the historical default). Unknown names are rejected.\nRequires `version` to be set."
    elements: str
  version:
    type: str
    description:
    - Target firmware version.
'''

EXAMPLES = r'''
---
- name: Run firmware on all tray resources
  nvidia.infra_controller.tray_firmware:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"

- name: Run firmware on a specific tray
  nvidia.infra_controller.tray_firmware:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    id: "{{ resource_id }}"
'''

RETURN = r'''
---
result:
    description: The action result.
    type: dict
    returned: always
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import ActionResource


ARGUMENT_SPEC = dict(
filter=dict(type='dict', options=dict(
    component_ids=dict(type='list', elements='str'),
    ids=dict(type='list', elements='str'),
    rack_id=dict(type='str'),
    rack_name=dict(type='str'),
    slot_id=dict(type='int'),
    type=dict(type='str', choices=['compute', 'switch', 'powershelf']),
)),
id=dict(type='str'),
site_id=dict(type='str'),
targets=dict(type='list', elements='str'),
version=dict(type='str'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/carbide/tray/firmware',
    'resource_item_path': '/v2/org/{org}/carbide/tray/{id}/firmware',
    'method': 'PATCH',
    'body_fields': ['site_id', 'version', 'targets', 'filter'],
    'query_fields': [],
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    ActionResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
