#!/usr/bin/python
# -*- coding: utf-8 -*-
# This file is auto-generated by scripts/generate.py. Do not edit manually.

# SPDX-FileCopyrightText: Copyright (c) 2026 Fabien Dupont
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: nvidia.infra_controller.vpc
short_description: Manage VPC resources
description:
- VPC defines the networking isolation boundary for Tenant's Instances.
version_added: 1.0.0
author: Fabien Dupont
extends_documentation_fragment:
- nvidia.infra_controller.auth
options:
  description:
    type: str
    description:
    - Optional description for the VPC
  id:
    type: str
    description:
    - ID of the resource. Used for lookup.
  labels:
    type: dict
    description:
    - String key-value pairs describing VPC labels. Up to 10 key-value pairs can be specified
  name:
    type: str
    description:
    - Name of the VPC
  network_security_group_id:
    type: str
    description:
    - ID of the Network Security Group to attach to the VPC
  network_virtualization_type:
    type: str
    description:
    - Network virtualization type of the VPC. If no value is specified, then defaults to `FNN` if Site has native networking
      enabled, or `ETHERNET_VIRTUALIZER` if native networking is disabled. Flat VPCs hold instances on zero-DPU hosts (or
      hosts with their DPU in NIC mode) and are never auto-selected -- `FLAT` must be specified explicitly.
    choices:
    - ETHERNET_VIRTUALIZER
    - FNN
    - FLAT
  nv_link_logical_partition_id:
    type: str
    description:
    - ID of the default NVLink Logical Partition that GPUs for all Instances in the VPC will attach to
  power_resource_group:
    type: str
    description:
    - Power resource group to associate with the VPC. A non-empty value requires the Site's `dpsPowerManagement` capability
      to be `true`.
  routing_profile:
    type: str
    description:
    - Specify routing profile for the VPC. Only supported when `networkVirtualizationType` is set to `FNN`, or when `networkVirtualizationType`
      is omitted and Site has Native Networking enabled. Requires Tenant to have elevated privilege. Current accepted values
      are `privileged-internal`, `internal`, and `external`.
  routing_profile_overrides:
    type: str
    description:
    - Routing-profile properties to overlay on the resolved named profile. Only supported for FNN VPCs and requires `TargetedInstanceCreation`
      to be effective for the Tenant at the VPC's Site. `routingProfile` may be omitted when the Site and Tenant configuration
      select a named profile.
  site_id:
    type: str
    description:
    - ID of the Site where the VPC should be created
  slaac_enabled:
    type: bool
    description:
    - When true, Core allocates a `/64` to each instance interface that includes IPv6 and retains the prefix without assigning
      a concrete IPv6 host address. It is supported only for FNN VPCs and fixed during creation. False or omission disables
      SLAAC. Before persistence, REST requires `vpcSlaac` in the latest successfully stored configuration inventory for the
      selected Site. Periodic Site inventory reports whether Core supports this feature, so the stored value can lag a Core
      rollout. False or missing `vpcSlaac` returns 412 before REST persistence or workflow dispatch. This flag does not verify
      DPU agent versions. When a new API server release is deployed, DPU agents roll forward, and instance network configuration
      may fail transiently until eligible agents converge. NICo does not yet configure router advertisements (RAs); that support
      is tracked by https://github.com/NVIDIA/infra-controller/issues/2398.
  state:
    type: str
    description:
    - Desired state of the resource.
    choices:
    - present
    - absent
  vni:
    type: int
    description:
    - Explicitly requested VNI for the VPC
  vpc_id:
    type: str
    description:
    - 'ID path parameter: vpc_id.'
  wait:
    type: bool
    description:
    - Wait for the resource to reach the desired state.
  wait_timeout:
    type: int
    description:
    - Timeout in seconds for wait operations.
'''

EXAMPLES = r'''
---
- name: Create a VPC
  nvidia.infra_controller.vpc:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: present
    name: "my-vpc"

- name: Delete a VPC
  nvidia.infra_controller.vpc:
    api_url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    org: "{{ org }}"
    state: absent
    name: "my-vpc"
'''

RETURN = r'''
---
resource:
    description: The resource details.
    type: dict
    returned: when state is present
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.nvidia.infra_controller.plugins.module_utils.common import get_auth_argument_spec
from ansible_collections.nvidia.infra_controller.plugins.module_utils.resource import CrudResource


ARGUMENT_SPEC = dict(
description=dict(type='str'),
id=dict(type='str'),
labels=dict(type='dict'),
name=dict(type='str'),
network_security_group_id=dict(type='str'),
network_virtualization_type=dict(type='str', choices=['ETHERNET_VIRTUALIZER', 'FNN', 'FLAT']),
nv_link_logical_partition_id=dict(type='str'),
power_resource_group=dict(type='str'),
routing_profile=dict(type='str'),
routing_profile_overrides=dict(type='str'),
site_id=dict(type='str'),
slaac_enabled=dict(type='bool'),
state=dict(type='str', choices=['present', 'absent']),
vni=dict(type='int'),
vpc_id=dict(type='str'),
wait=dict(type='bool'),
wait_timeout=dict(type='int'),
)

RESOURCE_CONFIG = {
    'resource_path': '/v2/org/{org}/nico/vpc/{vpcId}/virtualization',
    'resource_item_path': '/v2/org/{org}/nico/vpc/{vpcId}',
    'id_param': 'vpcId',
    'name_field': 'name',
    'create_schema_fields': ['id', 'name', 'description', 'site_id', 'network_virtualization_type', 'slaac_enabled', 'routing_profile', 'routing_profile_overrides', 'power_resource_group', 'network_security_group_id', 'vni', 'nv_link_logical_partition_id', 'labels'],
    'update_schema_fields': ['name', 'description', 'network_security_group_id', 'nv_link_logical_partition_id', 'routing_profile_overrides', 'power_resource_group', 'labels'],
    'scope_fields': ['site_id'],
    'ready_statuses': ['Ready'],
    'error_statuses': ['Error'],
    'no_create': False,
    'delete_body_fields': [],
    'version_field': None,
}


def main():
    auth_spec = get_auth_argument_spec()
    auth_spec.update(ARGUMENT_SPEC)
    module = AnsibleModule(argument_spec=auth_spec, supports_check_mode=True)
    CrudResource(module, RESOURCE_CONFIG).run()


if __name__ == "__main__":
    main()
